### ISSUE TITLE
NaN Data Error

### ISSUE THREAD

**Issue by osu-sustainability** [OSU-Sustainability-Office/kilowatt-crackdown#1] opened 2018-04-26 01:46 UTC
Monitor for NaN calculations and other data errors.

**Comment by jackrwoods** [comment] 2018-04-26 21:11
The bug appears to last for 15 minutes at a time, and occurred again at around 1:40pm on 04/26/2018. In the limited time I had, I:
 - Noticed that 2 consecutive daily calculations were resulting in large consumption.
 - The calculations are being made correctly, however, there are 15 minute intervals with radically different meter readings than the rest of the data.

I believe that the calculator is coincidentally selecting one of these poor data points, and performing a calculation using an incorrect meter reading. This would result in 2 consecutive days of high consumption, since daily consumption is calculated using the end-of-day meter reading from the previous day.
[I have committed, what I believe, is a patch for this bug](https://github.com/OSU-Sustainability-Office/kilowatt-crackdown/commit/36ddd9a9cb009e51c3cf56a4e4cf263dd819224c). The calculation script flags any daily consumption calculations greater than 5,000 KWh, and searches for a data point that will result in a more reasonable calculation. Although this increases daily consumption for that day, this also results in a 1:1 decrease in consumption for the following day. An average taken over the two days will be accurate.

This code has not been pushed to the S3 bucket, but will be pushed once I can confirm that it fixes the bug.

**Closed as completed** 2018-05-10 20:54 UTC
Labels: complete, priority-high
